### ISSUE TITLE
Mini vMac crashes after compiling and exporting iPadOS 13.3.1 Beta 1 iPad 7th Generation

### ISSUE THREAD

**Issue by snes666** [zydeco/minivmac4ios#34] opened 2019-12-30 20:31 UTC
Im using a brand new iPad 7th generation I developed and exported the code using Xcode 11.1 and I put the right rom in and everything and it keeps on crashing upon startup
can you possibly add support???

**Comment by zydeco** [comment] 2019-12-30 22:32
Where does it crash? Can you upload the crash log, or the error message if you run it from Xcode?
You can get crash logs from Xcode selecting the device from the “Devices and Simulators” window.

Jesús A. Álvarez

**Comment by snes666** [comment] 2019-12-30 23:25
It crashes upon opening on my iPad it's not jailbroken

**Comment by zydeco** [comment] 2020-01-28 19:27
Closing this issue, I have tested on the release version of iPad OS 13.3.1 and can’t reproduce any crash at start. If you can still reproduce it please add a crash log.

**Closed by zydeco** 2020-01-28 19:27 UTC
Labels: incomplete

**Comment by zydeco** [comment] 2020-01-29 18:17
Looks like it could be caused by a bug in iOS 13.3.1, which would also explain why I couldn’t reproduce it:
https://twitter.com/rileytestut/status/1222567119901974529

> strange, looks like iOS 13.3.1 breaks apps sideloaded with non-developer Apple IDs....but only if they contain embedded frameworks? 🤔 Includes apps installed the “official” way via Xcode too...
